In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv("synthetic_health_triage_data.csv", sep = ",")
data.head()

age  Symptom_duration_days  severity  fever  cough  chest_pain  \
0   52                     12         1      1      0           0   
1   60                      4         2      1      0           0   
2    3                      4         2      0      0           1   
3   78                      0         1      1      0           0   
4   87                     11         1      0      0           0   

   shortness_of_bredth  nausea  vomiting  diarrhea  dizziness  fatigue  \
0                    0       0         0         0          0        0   
1                    0       0         0         1          0        0   
2                    1       0         0         0          0        0   
3                    0       0         1         0          1        1   
4                    0       0         0         0          0        1   

   diabetes  hypertension  asthma  risk_level  
0         0             1       0           0  
1         0             0       1           1  
2         0             0       0           2  
3         0             1       0           0  
4         0             1       0           1

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    1500 non-null   int64
 1   Symptom_duration_days  1500 non-null   int64
 2   severity               1500 non-null   int64
 3   fever                  1500 non-null   int64
 4   cough                  1500 non-null   int64
 5   chest_pain             1500 non-null   int64
 6   shortness_of_bredth    1500 non-null   int64
 7   nausea                 1500 non-null   int64
 8   vomiting               1500 non-null   int64
 9   diarrhea               1500 non-null   int64
 10  dizziness              1500 non-null   int64
 11  fatigue                1500 non-null   int64
 12  diabetes               1500 non-null   int64
 13  hypertension           1500 non-null   int64
 14  asthma                 1500 non-null   int64
 15  risk_level             1500 non-null  

In [4]:
data.describe()

age  Symptom_duration_days     severity        fever  \
count  1500.000000            1500.000000  1500.000000  1500.000000   
mean     44.767333               6.601333     1.705333     0.386000   
std      25.622130               4.026728     0.783314     0.486993   
min       1.000000               0.000000     1.000000     0.000000   
25%      22.750000               3.000000     1.000000     0.000000   
50%      44.000000               7.000000     2.000000     0.000000   
75%      68.000000              10.000000     2.000000     1.000000   
max      89.000000              13.000000     3.000000     1.000000   

             cough   chest_pain  shortness_of_bredth       nausea  \
count  1500.000000  1500.000000          1500.000000  1500.000000   
mean      0.302667     0.150000             0.156667     0.142000   
std       0.459565     0.357191             0.363607     0.349167   
min       0.000000     0.000000             0.000000     0.000000   
25%       0.000000     0.000000             0.000000     0.000000   
50%       0.000000     0.000000             0.000000     0.000000   
75%       1.000000     0.000000             0.000000     0.000000   
max       1.000000     1.000000             1.000000     1.000000   

          vomiting     diarrhea    dizziness      fatigue     diabetes  \
count  1500.000000  1500.000000  1500.000000  1500.000000  1500.000000   
mean      0.113333     0.092667     0.208000     0.343333     0.133333   
std       0.317106     0.290061     0.406012     0.474980     0.340048   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     1.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

       hypertension       asthma   risk_level  
count   1500.000000  1500.000000  1500.000000  
mean       0.156000     0.085333     0.520667  
std        0.362976     0.279470     0.715015  
min        0.000000     0.000000     0.000000  
25%        0.000000     0.000000     0.000000  
50%        0.000000     0.000000     0.000000  
75%        0.000000     0.000000     1.000000  
max        1.000000     1.000000     2.000000

In [5]:
data.isnull().sum()

age                      0
Symptom_duration_days    0
severity                 0
fever                    0
cough                    0
chest_pain               0
shortness_of_bredth      0
nausea                   0
vomiting                 0
diarrhea                 0
dizziness                0
fatigue                  0
diabetes                 0
hypertension             0
asthma                   0
risk_level               0
dtype: int64

In [6]:
data.columns

Index(['age', 'Symptom_duration_days', 'severity', 'fever', 'cough',
       'chest_pain', 'shortness_of_bredth', 'nausea', 'vomiting', 'diarrhea',
       'dizziness', 'fatigue', 'diabetes', 'hypertension', 'asthma',
       'risk_level'],
      dtype='object')

In [7]:
data.shape

(1500, 16)

In [8]:
x = data.drop(columns = ["risk_level"])
y = data["risk_level"]

In [9]:
x

age  Symptom_duration_days  severity  fever  cough  chest_pain  \
0      52                     12         1      1      0           0   
1      60                      4         2      1      0           0   
2       3                      4         2      0      0           1   
3      78                      0         1      1      0           0   
4      87                     11         1      0      0           0   
...   ...                    ...       ...    ...    ...         ...   
1495   70                      2         2      1      1           0   
1496    9                      7         3      1      1           0   
1497   27                     11         1      1      0           0   
1498   78                      1         1      1      0           0   
1499   60                      1         2      0      0           0   

      shortness_of_bredth  nausea  vomiting  diarrhea  dizziness  fatigue  \
0                       0       0         0         0          0        0   
1                       0       0         0         1          0        0   
2                       1       0         0         0          0        0   
3                       0       0         1         0          1        1   
4                       0       0         0         0          0        1   
...                   ...     ...       ...       ...        ...      ...   
1495                    0       0         0         0          0        0   
1496                    0       0         0         0          1        1   
1497                    0       0         0         0          0        0   
1498                    0       0         0         1          0        0   
1499                    0       0         0         0          1        1   

      diabetes  hypertension  asthma  
0            0             1       0  
1            0             0       1  
2            0             0       0  
3            0             1       0  
4            0             1       0  
...        ...           ...     ...  
1495         1             0       0  
1496         1             1       0  
1497         1             0       0  
1498         0             0       0  
1499         1             1       0  

[1500 rows x 15 columns]

In [10]:
y

0       0
1       1
2       2
3       0
4       1
       ..
1495    0
1496    2
1497    0
1498    0
1499    0
Name: risk_level, Length: 1500, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42,stratify=y)

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
model = LogisticRegression(multi_class = "multinomial", solver = "lbfgs", max_iter = 1000, class_weight = "balanced")

In [17]:
model.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000,
                   multi_class='multinomial')

In [18]:
y_pred = model.predict(X_test_scaled)

In [19]:
from sklearn.metrics import confusion_matrix, classification_report

In [20]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[134  25  24]
 [ 15  57   6]
 [  4   1  34]]
              precision    recall  f1-score   support

           0       0.88      0.73      0.80       183
           1       0.69      0.73      0.71        78
           2       0.53      0.87      0.66        39

    accuracy                           0.75       300
   macro avg       0.70      0.78      0.72       300
weighted avg       0.78      0.75      0.76       300



In [21]:
import joblib

In [22]:
joblib.dump(model, "model.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']